import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import supabaseAuthRouter from "./supabase-auth";
import usersRouter from "./users";
import ticketsRouter from "./tickets";
import socialRouter from "./social";
import followsRouter from "./follows";
import moviesRouter from "./movies";
import notificationsRouter from "./notifications";
import bookmarksRouter from "./bookmarks";
import chatRouter from "./chat";
import partyRouter from "./party";
import storageRouter from "./storage";
import chainsRouter from "./chains";
import feedRouter from "./feed";
import embedsRouter from "./embeds";
import reportsRouter from "./reports";
import onboardingRouter from "./onboarding";
import badgesRouter from "./badges";
import supporterRouter from "./supporter";
import pageVerifyRouter from "./page-verification";
import pushRouter from "./push";
import adminRouter from "./admin";
import draftsRouter from "./drafts";
import settingsRouter from "./settings";
import wikiRouter from "./wiki";
import personRouter from "./person";
import characterRouter from "./character";

const router: IRouter = Router();

router.use("/", healthRouter);
router.use("/auth", authRouter);
router.use("/auth", supabaseAuthRouter);
router.use("/onboarding", onboardingRouter);
router.use("/users", usersRouter);
router.use("/users", followsRouter);
router.use("/tickets", ticketsRouter);
router.use("/tickets", socialRouter);
router.use("/movies", moviesRouter);
router.use("/notifications", notificationsRouter);
router.use("/bookmarks", bookmarksRouter);
router.use("/chat", chatRouter);
router.use("/party", partyRouter);
router.use("/storage", storageRouter);
router.use("/chains", chainsRouter);
router.use("/feed", feedRouter);
router.use("/embeds", embedsRouter);
router.use("/reports", reportsRouter);
router.use("/badges", badgesRouter);
router.use("/supporter", supporterRouter);
router.use("/page-verify", pageVerifyRouter);
router.use("/push", pushRouter);
router.use("/admin", adminRouter);
router.use("/drafts", draftsRouter);
router.use("/settings", settingsRouter);
router.use("/wiki", wikiRouter);
router.use("/person", personRouter);
router.use("/character", characterRouter);

export default router;
